name: Deploy to Cloud Run

env:
  PROJECT_ID: gpt-persona
  SERVICE_NAME: restapi
  REGION: us-central1

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deploy to"
        required: true
        type: choice
        options: 
          - development
          - qa
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Deploy to Cloud Run using Dockerfile
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }}-${{ github.event.inputs.environment }} \
          --region ${{ env.REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --memory 512Mi \
          --cpu 1 \
          --max-instances 10 \
          --min-instances 0 \
          --timeout 300 \
          --source . \
          --port 8080
